name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *' # Exécute quotidiennement à minuit
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: anasmnasri2023
          outputs: dist/github-contribution-grid-snake.svg
