name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Tous les jours à minuit
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: anasmnasri2023
          outputs: |
            ./github-contribution-grid-snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Snake Animation"
          add: "github-contribution-grid-snake.svg"
